import type { Knex } from 'knex';
import db from '../config/database';
import { AppError } from '../utils/errors';
import { monthName } from './payslip.calc';

/**
 * One definition of "this payroll month is closed", and one of "these payslips are out of date".
 *
 * Both used to live inside payslip.service as module-private helpers, which meant anything OUTSIDE
 * payroll that could move a paid month — regularisation, most obviously — had to invent its own
 * version. Regularisation's was `run.status === 'locked'` and nothing else, so a request could be
 * approved into a month frozen for the OTHER reason (legacy payslips), where the correction could
 * never reach money: attendance changed, the employee was told it was fixed, and every write path
 * that could have paid it refused. Two definitions of closed, drifting apart, is how that happens.
 *
 * This module holds the single definition. payslip.service re-exports its own thin throwing
 * wrapper so its existing call sites read unchanged.
 */

/**
 * Payslips at or below this version were produced by rules that no longer exist in the codebase,
 * and cannot be reproduced at all. Migration 002 stamped them.
 *
 * Anything at 2 or above was generated by this lineage. A later CALC_VERSION bump changes what a
 * recompute would *produce*, but it does not make those months unreproducible — so it must not
 * retroactively close them. See the long note on monthWriteState.
 */
export const LEGACY_CALC_VERSION = 1;

/** Advisory-lock key2 for a payroll month: stable, ordered, and collision-free across years. */
export const monthKeyOf = (month: number, year: number) => year * 12 + month;

export type MonthClosedReason = 'locked' | 'legacy';

export interface MonthWriteState {
  writable: boolean;
  reason: MonthClosedReason | null;
  /** Human sentence naming the remedy, or '' when writable. Callers append their own consequence. */
  message: string;
}

/**
 * Is this month open to writes, and if not, why?
 *
 * Deliberately scoped to the MONTH rather than to one employee's row. A month is closed as a
 * whole: its run totals are an aggregate over every slip in it, so writing a single new slip into
 * a closed month moves figures for a month that has already been paid — even when that particular
 * employee had no slip of their own to protect.
 *
 * Two things close a month, and only these two:
 *   • it is LOCKED — the money went out, so nothing may move; or
 *   • it holds legacy payslips (calc_version 1) that cannot be reproduced at all.
 *
 * It deliberately does NOT close a month merely for holding payslips one version behind the
 * current rules. That check used to be `calc_version < CALC_VERSION`, which meant every bump
 * instantly bricked every open draft: un-runnable, un-correctable, un-regenerable, with no exit
 * but hand-editing the database — while still being lockable and payable at whatever partial
 * figures the last preview happened to hold. An unpaid draft under old rules is precisely the
 * thing that SHOULD be re-run: re-running restamps it at the current version, which is how a
 * month leaves the mixed state rather than being trapped in it.
 *
 * Pass `cx` to evaluate inside a transaction — the callers that then write must, or a concurrent
 * lock can land between the check and the write.
 */
export async function monthWriteState(
  month: number, year: number, cx: Knex | Knex.Transaction = db,
): Promise<MonthWriteState> {
  const run = await cx('payroll_runs').where({ month, year }).first();
  if (run?.status === 'locked') {
    return {
      writable: false,
      reason: 'locked',
      message: `${monthName(month)} ${year} is locked`,
    };
  }

  const legacy = await cx('payslip_history')
    .where({ month, year }).where('calc_version', '<=', LEGACY_CALC_VERSION).count('id as c').first();
  if (Number((legacy as any)?.c ?? 0) > 0) {
    return {
      writable: false,
      reason: 'legacy',
      message: `${monthName(month)} ${year} was calculated under pay rules that no longer exist and is frozen`,
    };
  }

  return { writable: true, reason: null, message: '' };
}

/** Throwing form. `consequence` completes the sentence: "<month> is locked — <consequence>." */
export async function assertMonthWritable(
  month: number, year: number, consequence: string, cx: Knex | Knex.Transaction = db,
): Promise<void> {
  const state = await monthWriteState(month, year, cx);
  if (!state.writable) throw new AppError(`${state.message} — ${consequence}.`, 409);
}

export interface StalePayslip {
  employee_id: number;
  /** When this employee's attendance was last touched, later than their payslip was priced. */
  attendance_touched_at: string;
}

/**
 * Payslips that were priced BEFORE the attendance they are supposed to reflect.
 *
 * Derived, never flagged. A stored payslip is out of date exactly when one of that employee's
 * attendance rows for the month has a later `updated_at` than the payslip does — so a successful
 * re-price clears it as a side effect of doing its job, and there is no "forgot to set the flag"
 * bug available. It also costs nothing to extend: a bulk upload or a leave approval writes
 * attendance the same way a regularisation does, so all three are caught by one query.
 *
 * Per employee rather than per month, and that carries weight: a 400-person run writes its slips
 * in a loop over minutes, so an attendance change mid-run leaves some slips stale and others fine.
 *
 * Correct in the direction that matters. A payslip is stamped with a timestamp taken BEFORE the
 * compute that produced it read anything (see `pricedAt` in refreshPayslipAfterAttendanceChange and
 * runPayroll), never with `now()` at write time. So an attendance write landing between the read and
 * the write is necessarily NEWER than the payslip that does not contain it, and shows up here.
 *
 * That ordering is load-bearing and cannot be relaxed to a write-time clock: no attendance writer
 * takes the month lock — not the two uploads, not leave approval, not regularisation itself — so
 * nothing else serialises that window, and `lockRun` refuses on this check, which means a clean
 * result is read as "safe to pay".
 *
 * The opposite direction is harmless: a false "stale" costs one redundant re-run, nothing more.
 */
export async function stalePayslips(
  month: number, year: number, cx: Knex | Knex.Transaction = db,
): Promise<StalePayslip[]> {
  // Business dates are TEXT 'YYYY-MM-DD', so a zero-padded lexical range is the correct filter
  // and uses the (employee_id, date) index. '-31' is a safe upper bound in every month.
  const mm = String(month).padStart(2, '0');
  const rows = await cx('payslip_history as ph')
    .join('attendance_records as ar', function joinOn() {
      this.on('ar.employee_id', '=', 'ph.employee_id')
        .andOn('ar.updated_at', '>', 'ph.updated_at');
    })
    .where({ 'ph.month': month, 'ph.year': year })
    .whereBetween('ar.date', [`${year}-${mm}-01`, `${year}-${mm}-31`])
    .groupBy('ph.employee_id')
    .select('ph.employee_id')
    .max({ attendance_touched_at: 'ar.updated_at' });

  return rows.map((r: any) => ({
    employee_id: Number(r.employee_id),
    attendance_touched_at: r.attendance_touched_at,
  }));
}
